feat: set exit-and-install redist mandatory
nervosnetwork/neuron pull request #2202
Opened 2021-12-01 02:57 UTC by Keith-CY

2021-12-02 07:34 UTC, yuche approved these changes

2021-12-03 07:57 UTC, kellyshang requested changes

2021-12-03 07:57 UTC, kellyshang commented on packages/neuron-wallet/src/locales/en.ts
>          detail: `The embedded CKB node in Neuron requires x64 version of Microsoft Visual C++ Redistributable component to be installed to work properly. You have to install it to enable the internal
```suggestion
        detail: `The embedded CKB node in Neuron requires x64 version of Microsoft Visual C++ Redistributable component to be installed to work properly. You have to install it to enable the internal node.`,
```

2021-12-03 07:57 UTC, kellyshang commented on packages/neuron-wallet/src/locales/zh-tw.ts
>          detail: 'Neuron 內置的 CKB 節點需要安裝 x64 版本的 Microsoft Visual C++ Redistributable 才能正常運行。您需要安裝該組件來啟動內置節點。如果您使用外部節點，也可以跳過該步驟。',
```suggestion
        detail: 'Neuron 內置的 CKB 節點需要安裝 x64 版本的 Microsoft Visual C++ Redistributable 才能正常運行。您需要安裝該組件來啟動內置節點。',
```

2021-12-03 07:57 UTC, kellyshang commented on packages/neuron-wallet/src/locales/zh.ts
>          detail: 'Neuron 内置的 CKB 节点需要安装 x64 版本的 Microsoft Visual C++ Redistributable 才能正常运行。您需要安装该组件来启用内置节点。如果您使用外部节点，也可以跳过该步骤。',
```suggestion
        detail: 'Neuron 内置的 CKB 节点需要安装 x64 版本的 Microsoft Visual C++ Redistributable 才能正常运行。您需要安装该组件来启用内置节点。',
```

2021-12-03 08:15 UTC, kellyshang approved these changes

2021-12-03 08:15 UTC, merged