fix: New UI menu bar issuesOC
nervosnetwork/neuron pull request #2709
Opened 2023-06-09 06:30 UTC by JeffreyMa597

What problem does this PR solve?
------
As title.

Ref:https://github.com/Magickbase/neuron-public-issues/issues/158

Check List
------
1、List
2、Detail

### Test
e2e Test
### Task
none

2023-06-09 10:02 UTC, yanguoyu commented on packages/neuron-ui/src/styles/mixin.scss
> +@mixin cursor-mode {
Is it necessary to define one property with `mixin`? I think `cursor: pointer` is clear to replace `@include cursor-mode;`

2023-06-13 07:33 UTC, yanguoyu approved these changes

2023-06-13 11:52 UTC, WhiteMinds commented
Scroll bars and unexpected overflows when shrinking windows

<img width="1099" alt="image" src="https://github.com/nervosnetwork/neuron/assets/9160743/26dc66c3-11b8-40c1-8bcf-d3a04a5c3e98">

The language option is missing in the settings, I can't switch languages.

2023-06-13 11:52 UTC, WhiteMinds requested changes
Scroll bars and unexpected overflows when shrinking windows

<img width="1099" alt="image" src="https://github.com/nervosnetwork/neuron/assets/9160743/26dc66c3-11b8-40c1-8bcf-d3a04a5c3e98">

The language option is missing in the settings, I can't switch languages.

2023-06-14 09:50 UTC, JeffreyMa597 commented
> Scroll bars and unexpected overflows when shrinking windows

updated. 
<img width="600" alt="image" src="https://github.com/nervosnetwork/neuron/assets/22511289/149e181a-39bd-4401-ae83-9e14dc292441">


> The language option is missing in the settings, I can't switch languages.

You can select them over here.
<img width="600" alt="image" src="https://github.com/nervosnetwork/neuron/assets/22511289/b1a84b15-0d48-4abc-b1d8-4c7cb41d16fd">

2023-06-14 09:52 UTC, WhiteMinds approved these changes

2023-06-14 09:54 UTC, WhiteMinds commented
> You can select them over here.

I can't believe I looked at it 3 times and didn't notice it 🫠. Is it my problem or a UI issue?

2023-06-14 10:00 UTC, Keith-CY commented
> > You can select them over here.
> 
> I can't believe I looked at it 3 times and didn't notice it 🫠. Is it my problem or a UI issue?

@Danie0918 @Sven-TBD please check if it is user friendly

2023-06-15 01:43 UTC, Danie0918 commented
> > > You can select them over here.
> > 
> > 
> > I can't believe I looked at it 3 times and didn't notice it 🫠. Is it my problem or a UI issue?
> 
> @Danie0918 @Sven-TBD please check if it is user friendly

Language setting is not a high-frequency operation, so it is reasonable to put it in the settings and continue the previous user habits. The problem here is that the language of the current settings is weakened, so users can't find it quickly, and this needs to be optimized by adding an icon or deepening the color.  @Kirl

2023-06-15 02:40 UTC, Kirl70 commented
> > > > You can select them over here.
> > > 
> > > 
> > > I can't believe I looked at it 3 times and didn't notice it 🫠. Is it my problem or a UI issue?
> > 
> > 
> > @Danie0918 @Sven-TBD please check if it is user friendly
> 
> Language setting is not a high-frequency operation, so it is reasonable to put it in the settings and continue the previous user habits. The problem here is that the language of the current settings is weakened, so users can't find it quickly, and this needs to be optimized by adding an icon or deepening the color. @Kirl70

Icons have been added in front of the options as an indication:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=1165%3A12477&t=JhtdSRXHKrCkhAGF-1
<img width="695" alt="image" src="https://github.com/nervosnetwork/neuron/assets/106060898/16db3ef4-3e26-43b8-9da4-dadb4f5ee53f">

2023-06-15 08:04 UTC, JeffreyMa597 commented
> Icons have been added in front of the options as an indication:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=1165%3A12477&t=JhtdSRXHKrCkhAGF-1

Updated.

2023-06-16 08:21 UTC, FrederLu approved these changes

2023-06-26 01:42 UTC, devchenyan approved these changes

2023-06-26 01:42 UTC, merged