Refactor: replace 'HexUtils' with lumos functionalities
nervosnetwork/neuron pull request #2718
Opened 2023-06-13 03:14 UTC by zhangyouxin

## Description

This PR replaces some hexutil functions with `@ckb-lumos/code` and `@ckb-lumos/bi`, they are more tested and reliable.

Ref: https://github.com/Magickbase/neuron-public-issues/issues/187

2023-06-13 10:41 UTC, zhangyouxin commented
> There are some [`removePrefix`](https://github.com/nervosnetwork/neuron/blob/03678574eb17629626bc6470c93cf5f0758a9755/packages/neuron-wallet/src/models/asset-account-info.ts#L247-L249) we can refactor with `bytes.hexify(bytes.concat(hash1, hash2))`, after doing this, we can move the `addPrefix` and `removePrefix` to ledger module, this can reduce the complexity of the project by eliminating one module

Good advice about the  [`removePrefix`](https://github.com/nervosnetwork/neuron/blob/03678574eb17629626bc6470c93cf5f0758a9755/packages/neuron-wallet/src/models/asset-account-info.ts#L247-L249) you mentioned here, but there are some other usages like [findSignPathForCheque](https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-wallet/src/models/asset-account-info.ts#L289-L290) that may cause bug if `removePrefix` is moved to ledger module, anyway, I'm diving into the business logic here and get rid of `removePrefix` safely.

2023-06-13 11:01 UTC, zhangyouxin commented
> 

This is comprehensive but it's assuming that the input param `chequeLockArgs` starts with `0x`, if not, the `byte.bitify` function will throw an error. we need to be careful here

2023-06-13 13:16 UTC, zhangyouxin commented
in [this commit](https://github.com/nervosnetwork/neuron/pull/2718/commits/16a7700bc2c9678d091170443d6833ca16daa906) I have removed the `HexUtil` module and changed some tests, please take a look @homura @yanguoyu

2023-06-13 14:08 UTC, homura commented on packages/neuron-wallet/src/models/asset-account-info.ts
> +    const senderLockHash = bytes.bytify(`0x${chequeLockArgs.slice(42)}`)
```ts
const checkLockArgs = bytes.bytify(chequeLockArgs)
const receiverLockHash = checkLockArgs.slice(0, 20)
const receiverLockHash = checkLockArgs.slice(20)
```

Maybe we can also use some more readable approach

```ts
const ChequeLockArgsCodec = molecule.struct({
  receiverLockHash: Bytes20,
  senderLockHash: Bytes20,
}, [
  'receiverLockHash',
  'senderLockHash'
])

const { receiverLockHash, senderLockHash } = ChequeLockArgsCodec.unpack(chequeLockArgs)
```

2023-06-13 14:34 UTC, zhangyouxin commented on packages/neuron-wallet/tests/models/chain/block-header.test.ts
> +    expect(result.timestamp).toEqual('1557311767') // 0x5cd2b117
Yes magic numebers are not readable so I commented the original value from test case in the same file to make this test case readable.
But using logic code to calculate them is making this test case rewriting the logic of being-tested code, looks unnecessary

2023-06-13 14:38 UTC, zhangyouxin commented on packages/neuron-wallet/src/models/chain/input.ts
> +      since: BI.from(this.since || 0).toHexString(),
Some test cases gives `undefined` for this value, making it not convertable to `BI`, while in real world business `since` is default to `0x0`

2023-06-13 14:49 UTC, zhangyouxin commented on packages/neuron-wallet/src/models/chain/script.ts
>    public calculateBytesize(): number {
updated

2023-06-14 07:59 UTC, WhiteMinds requested changes

2023-06-14 09:31 UTC, yanguoyu commented on yarn.lock
> +  integrity sha512-5v8E2XjZDFzK7K87eSwC7AJcAkcLt5xYZ4+yTPDAW1i7C93oOY1dnr4BaQM7un4Hm+GmghuiPvevWwlca5PwDA==
IMO, `yarn.lock` was auto-created, should we edit it manually?

2023-06-14 09:47 UTC, WhiteMinds commented on yarn.lock
> +  integrity sha512-5v8E2XjZDFzK7K87eSwC7AJcAkcLt5xYZ4+yTPDAW1i7C93oOY1dnr4BaQM7un4Hm+GmghuiPvevWwlca5PwDA==
> IMO, `yarn.lock` was auto-created, should we edit it manually?

This seems to be a reorganization of the commits. You can see that the first commit removed `react-i18next@>=11.16.4`, and it was added back in the second commit, which caused the version of `react-i18next` to change.
So now all that needs to be done is to go back to the first commit, remove the unnecessary changes, and then reorganize it.

2023-06-18 07:48 UTC, zhangyouxin commented on yarn.lock
> +  integrity sha512-5v8E2XjZDFzK7K87eSwC7AJcAkcLt5xYZ4+yTPDAW1i7C93oOY1dnr4BaQM7un4Hm+GmghuiPvevWwlca5PwDA==
updated

2023-06-19 01:37 UTC, WhiteMinds approved these changes

2023-06-19 02:20 UTC, homura approved these changes

2023-06-19 04:49 UTC, zhangyouxin commented
Sorry I didn't notice that all commits should be "Verified", so I squashed all commits and signed it with my GPG key, then the squashed commit needs to be force pushed, will sign every commit in future.

2023-06-25 08:44 UTC, homura commented
The conflicts are waiting for resolved

2023-06-26 05:57 UTC, FrederLu commented
@zhangyouxin 
What does this pr modify? What does QA need to verify? Or verify what kind of scene.

2023-06-27 00:40 UTC, zhangyouxin commented
> @zhangyouxin What does this pr modify? What does QA need to verify? Or verify what kind of scene.

This PR has changed some low level function dependencies, mostly used in the `packages/neuron-wallet` package, though it's not a big change, it may affect many functionalities,  such as Cell Service, Transaction Service, QA may need adequate regression test for `syncing`, `show balance`, `send transaction` and so on.

2023-06-27 12:02 UTC, littleLip520 commented
use multisig address do transaction to normal address occur an erorr.
<img width="948" alt="image" src="https://github.com/nervosnetwork/neuron/assets/26523791/66057511-e17d-4bdd-9cd0-cba68d674ac7">

[main.log](https://github.com/nervosnetwork/neuron/files/11881718/main.log)

2023-06-28 08:27 UTC, littleLip520 commented
after using  asset account do transaction. seems transaction detail did't match trans amount.   @zhangyouxin 
<img width="1093" alt="image" src="https://github.com/nervosnetwork/neuron/assets/26523791/be95efec-ea34-4865-9761-7ee55388d855">

2023-07-11 10:33 UTC, homura commented
@zhangyouxin any update of this ?

2023-07-14 08:18 UTC, zhangyouxin commented
/package

2023-07-14 08:20 UTC, zhangyouxin commented
> use multisig address do transaction to normal address occur an erorr. <img alt="image" width="948" src="https://user-images.githubusercontent.com/26523791/249142768-66057511-e17d-4bdd-9cd0-cba68d674ac7.png">
> 
> @zhangyouxin
> 
> [main.log](https://github.com/nervosnetwork/neuron/files/11881718/main.log)

I have merged develop branch, tested the feature on local machine and didn't meet the issue, is there more detail of condition to trigger the two issues?

2023-07-19 09:16 UTC, zhangyouxin commented
> after using asset account do transaction. seems transaction detail did't match trans amount. @zhangyouxin <img alt="image" width="1093" src="https://user-images.githubusercontent.com/26523791/249402319-be95efec-ea34-4865-9761-7ee55388d855.png">
> 
> add hash 0x521c210c81616f95bfa6ac63a427d5145c59ecdf4c4c79e6dcea9fe51fb18bb7

After confirmation with @FrederLu , we found that in this [transaction](https://pudge.explorer.nervos.org/transaction/0x521c210c81616f95bfa6ac63a427d5145c59ecdf4c4c79e6dcea9fe51fb18bb7), the user business is extracting 9999 sUDT from a cell with ACP lock. So both sudt receive amount and CKB change amount are correct value here.

2023-07-19 10:29 UTC, FrederLu approved these changes

2023-07-20 05:49 UTC, merged